<?php 
use Application\Utils\ApplicationConst;
use Application\Utils\DateHelper;
?>

<style>
.box-text-outline {
    background: #eeeeee;
    padding-top: 10px;
}
.answerInputRow{
	padding-top: 10px;
}

</style>

<div class="container container-body">
	<div class="box-header">アンケートの追加・修正</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-mx-12 text-left">
				<form class="form-horizontal" id="form-policy-survey" method="post"
				action="<?php echo $this->url('survey-management/default', array('action' => 'save')) ?>">
					<div id="createView"></div>
					<div id="createQuesstion"></div>
					<div class="heighthr"></div>
					<div class="form-group">
						<h5 class="col-md-2 col-sm-2">更新日</h5>
						<div id="datepicker" class="none-padding-left col-md-3 col-sm-4 col-xs-12 input-group date">
							<input id="createDate" name="createDate" type="text" class="createDate form-control">
							<span class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </span>
						</div>
					</div>
					<div class="form-group">
						<div id="errorCreateDate" style="display:none" class="col-md-offset-2 col-sm-offset-2 col-md-3 col-sm-4 col-xs-12">
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-2 col-sm-4 col-xs-12 pull-right">
							<button type="submit" class="btn col-md-12 col-sm-12 col-xs-12 btn-space btn-primary">保存</button> 
						</div>
						<div class="col-md-2 col-sm-4 col-xs-12 pull-right">
							<a href="survey-module-12-1-list-survey-common.html">
								<button type="button" class="btn col-md-12 col-sm-12 col-xs-12 btn-space btn-default">戻る</button>
							</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="modal fade dialog-position" id="pleaseWaitDialog" role="dialog">
	<div class="modal-dialog modal-sm">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">ID:12-1-2</h4>
			</div>
			<div class="modal-body">
				<p>登録確認画面</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default pull-left" data-dismiss="modal">戻る</button>
				<button type="button" class="btn btn-primary" 
					onClick="location.href = 'survey-module-12-1-3-edit-question-succeed.html'" data-dismiss="modal">はい</button>
			</div>
		</div> 
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/survey-management/survey-questions.js"> </script>
<script>
   $( document ).ready(function() {
	   SURVEY_QUESTIONS.initLoad();
    });   
</script>
