<div class="modal fade dialog-position" data-backdrop="static" id="deleteUserModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm dialog-position">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close btnCloseDeleteUser">&times;</button>
                <h4 class="modal-title">削除確認</h4>
            </div>
            <div class="modal-body message">
                
            </div>
            <div class="modal-footer">
                <input type="hidden" id="userIdDeleteUser" value="" />
                <input type="hidden" id="usernameDeleteUser" value="" />
                <input type="hidden" id="roleIdDeleteUser" value="" />                
                <button class="btn btn-default btnCloseDeleteUser">いいえ</button>
                <button class="btn btn-primary btnConfirmDeleteUser">はい</button>
            </div>
        </div>
    </div>
</div>