<div class="modal fade dialog-position" data-backdrop="static" id="deleteUserSuccessModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm dialog-position">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close btnConfirm">&times;</button>
                <h4 class="modal-title">削除済み</h4>
            </div>
            <div class="modal-body message">
               
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary btnConfirm">完了</button>
            </div>
        </div>
    </div>
</div>