<div id="exportTimeModal" class="modal dialog-position" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body ">
                <form id="frmExportData" method="POST" action="<?php echo $action;?>" class="form-horizontal">
                    <input type="hidden" name="exportType" id="exportType" value=""/>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label class="col-md-2 col-sm-2 form-check-input"><h5>開始月</h5></label>
                            <div id="startDateBox" class="col-md-10 col-sm-10 col-xs-12 input-group date inputTime">
                                <input type="text" readonly="" id="startMonth" name="startMonth" class="form-control" data-date-format="yyyy/mm" autocompleted="off">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>                                
                            </div>
                            <div class="col-md-10 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-2" style="padding-left: 0px;">
                                <span id="startMonth-error" style="display: none;" class="flag-notice"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label class="col-md-2 col-sm-2 form-check-input"><h5>終了月</h5></label>
                            <div id="endDateBox" class="col-md-10 col-sm-10 col-xs-12 input-group date inputTime">
                                <input type="text" readonly="" id="endMonth" name="endMonth" class="form-control" data-date-format="yyyy/mm" autocompleted="off">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>
                            <div class="col-md-10 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-2" style="padding-left: 0px;">
                                <span id="endMonth-error" style="display: none;" class="flag-notice"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3 col-md-offset-6 col-sm-3 col-sm-offset-6">
                            <button type="button" class="btn btn-space btn-default col-md-12 col-sm-12 col-xs-12 pull-right" data-dismiss="modal">キャンセル</button>
                        </div>
                        <div class="col-md-3 col-sm-3">
                            <input type="submit" name="submit" id="btnSubmitExportData" class="btn btn-space btn-primary col-md-12 col-sm-12 col-xs-12 pull-right" value="出力" />                            
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>