<div id="importUserConfirmModal" class="modal fade dialog-position"  role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">ユーザーアップロード</h4>
            </div>
            <div class="modal-body box-text">
                <h5>
                    <b>
                        <p><span class="total_insert"></span>レコードが正常にアップロードされる。</p>
                        <p class="flag-notice"><span class="total_delete"></span>レコードが正常に削除される。</p>
                    </b>
                </h5>
            </div>
            <div class="modal-footer">
                <div class="col-md-3 pull-right">
                    <button type="button" class="btn btn-primary col-md-12 btnSave">保存</button>
                </div>
                <div class="col-md-3 pull-right">
                    <button type="button" class="btn btn-default col-md-12 btnCancel">キャンセル</button>
                </div>
                <div class="col-md-3 pull-right">
                    <button type="button" class="btn btn-default col-md-12 btnBack">戻る</button>
                </div>
            </div>
        </div>

    </div>
</div>