<div id="importUserErrorModal" class="modal fade dialog-position"  role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">ユーザーアップロード</h4>
            </div>
            <div class="modal-body box-text error-message flag-notice over-flow-ie">
                
            </div>
            <div class="modal-footer">
                <div class="col-md-3 pull-right">
                    <button type="button" class="btn btn-default col-md-12 btnBack" data-dismiss="modal">戻る</button>
                </div>
                <div class="col-md-3 pull-right">
                    <button type="button" class="btn btn-default col-md-12 btnCancel" data-dismiss="modal">キャンセル</button>
                </div>
            </div>
        </div>

    </div>
</div>