<div class="modal fade dialog-position" data-backdrop="static" id="resetPasswordModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm dialog-position">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close btnCloseResetPasswordModal">&times;</button>
                <h4 class="modal-title">パスワードリセット</h4>
            </div>
            <form action="<?php echo $action; ?>" id="frmResetPassword">
                <div class="modal-body">                
                    <div class="row">
                        <label class="col-md-12">新しいパスワード</label> 
                        <div class="col-md-12"> <input type="password" class="form-control" id="newPassword" name="newPassword" /></div>
                        <input type="hidden" id="userIdResetPassword" name="userId" value="" />
                        <input type="hidden" id="usernameResetPassword" name="username" value="" />
                        <input type="hidden" id="roleIdResetPassword" name="roleId" value="" />
                    </div>                
                </div>
            
                <div class="modal-footer">                
                    <button type="button" class="btn btn-default btnCloseResetPasswordModal">キャンセル</button>
                    <button type="submit" class="btn btn-success">リセット</button>
                </div>
            </form>
        </div>
    </div>
</div>