<div class="modal fade dialog-position" data-backdrop="static" id="resetPasswordConfirmModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm dialog-position">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">パスワードリセット</h4>
            </div>
            <div class="modal-body message">
                
            </div>
            <div class="modal-footer">
                <button class="btn btn-default btnCancel">いいえ</button>
                <button class="btn btn-primary btnConfirm">はい</button>
            </div>
        </div>
    </div>
</div>