<?php
use Application\Utils\DateHelper;
/* @var $policy \Application\Entity\Policy */
$arrPdfFiles = $policy->getPdfFile() ? json_decode($policy->getPdfFile(), true) : array();
?>
<div class="row">
	<div class="col-md-2 col-sm-6 col-xs-12 pull-right">
		<button type="button"
			class="btn btn-space col-md-12 col-sm-12 col-xs-12 FPolicy <?php if(isset($policy_favourite) && is_array($policy_favourite) && count($policy_favourite) == 0 ):?> addFPolicy btn-success<?php else :?> removeFPolicy btn-warning<?php endif;?>">
			<?php if(isset($policy_favourite) && is_array($policy_favourite) && count($policy_favourite) == 0 ):?>
			<span class="icon-star"></span> お気に入りに登録 
			<?php else :?> 
			<span class="icon-star"></span> お気に入りから削除 
			<?php endif;?>
		</button>
	</div>
	<div class="col-md-2 col-sm-6 col-xs-12 pull-right">
		<a class="btn btn-space btn-success col-md-12 col-sm-12 col-xs-12"
			href="/policy/confirm-print/<?php echo $policy->getId()?>"
			target="_blank"> <span class="icon-print"></span> 印刷
		</a>
	</div>
</div>
<div class="clearfix"></div>
<div class="container-body container-body-detail row">
	<div class="box-header">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xm-12">
				<label>
					<h3>
						<b><?php echo $policy->getShortName();?></b>
					</h3>
				</label>
				<div class="heighthr"></div>
				<h4>
					<?php echo $policy->getName();?>
				</h4>
				<br/>
				<?php if(!empty($policy->getSummaryUpdate())):?>
				<h5>
					情報更新日：
					<?php echo DateHelper::convertTimestampToGengo($policy->getUpdateDateDisplay());?>
				</h5>
				<h5>更新内容の概要：</h5>
				<h5>
					<?php echo nl2br($policy->getSummaryUpdate());?>
				</h5>
				<?php endif;?>
			</div>

		</div>
	</div>
	<div class="box-data col-md-12">
		<div class="row">
			<table class="col-md-12 col-sm-12 col-xs-12 table-policy-mobile">
				<?php foreach ($glConfig['attributePolicyType'] as $key => $values):?>
				<?php if (isset($values['displayCreate']) && $values['displayCreate'] == 1 && isset($values['detailPolicy']) && $values['detailPolicy'] == 1) :?>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">
							<?php echo $values['value'];?>
						</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2">
						<span>
							<?php if(isset($attributes[$key])):?>
								<?php foreach ($attributes[$key] as $k => $vl):?>
									<?php echo $vl['value'];?> <br/>
								<?php endforeach;?> 
							<?php endif;?>
						</span>
					</td>
				</tr>
				<?php endif;?>
				<?php endforeach;?>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">目的</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2"><span> <?php echo nl2br($policy->getPurpose());?>
					</span>
					</td>
				</tr>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">対象者の詳細</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2"><span> <?php echo nl2br($policy->getDetailOfSupportArea());?>
					</span>
					</td>
				</tr>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">施策内容</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2"><span> <?php echo nl2br($policy->getContent());?>
					</span>
					</td>
				</tr>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">事業（実施）期間の詳細</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2"><span> <?php echo nl2br($policy->getDetailRecruitmentTime());?>
					</span>
					</td>
				</tr>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">チラシ・パンフレット</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2">
						<?php if ($arrPdfFiles) : ?> 
						<span> 
							<?php foreach ($arrPdfFiles as $file) : ?>
							<a href="<?php echo $this->url('download', array(
                                                'year' => DateHelper::convertTimestampToString($policy->getCreateDate(), 'Y'),
                                                'month' => DateHelper::convertTimestampToString($policy->getCreateDate(), 'm'),
                                                'day' => DateHelper::convertTimestampToString($policy->getCreateDate(), 'd'),
                                                'fileName' => basename($file),
                                            )) ?>"> 
								<img src="<?php echo $this->basePath(); ?>/images/oficina_pdf.png" width="40" height="35" alt="<?php echo basename($file); ?>" title="<?php echo basename($file); ?>"/>
							</a> 
							<?php endforeach; ?>
						</span> 
						<?php endif; ?>
					</td>
				</tr>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">ホームページ</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2">
					<span> 
						<a target="_blank" href="<?php $url = $policy->getHomepage(); if (!preg_match("~^(?:f|ht)tps?://~i", $url)) { $url = "http://" . $url; } echo $url;?>"><?php echo $policy->getHomepage()?></a>
					</span>
					</td>
				</tr>
				<tr class="title">
					<td class="title-search col-md-3 col-sm-4 col-xs-6">
						<h5 class="text-color-white">問い合わせ先</h5>
					</td>
					<td class="box-search col-md-9 col-sm-8 col-xs-6">
						<div class="col-md-12 col-sm-12 col-xs-12 pull-right"></div>
					</td>
				</tr>
				<tr class="content">
					<td colspan="2"><span> <?php echo nl2br($policy->getContact());?>
					</span>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-2 col-sm-6 col-xs-12 pull-right">
		<button type="button" class="btn btn-space col-md-12 col-sm-12 col-xs-12 FPolicy <?php if(isset($policy_favourite) && is_array($policy_favourite) && count($policy_favourite) == 0 ):?> addFPolicy btn-success <?php else :?> removeFPolicy btn-warning <?php endif;?>">
			<?php if(isset($policy_favourite) && is_array($policy_favourite) && count($policy_favourite) == 0 ):?>
			<span class="icon-star"></span> お気に入りに登録 
			<?php else :?> 
			<span class="icon-star"></span> お気に入りから削除 
			<?php endif;?>
		</button>
	</div>
	<div class="col-md-2 col-sm-6 col-xs-12 pull-right">
		<a class="btn btn-space btn-success col-md-12 col-sm-12 col-xs-12"
			href="/policy/confirm-print/<?php echo $policy->getId()?>"
			target="_blank"> <span class="icon-print"></span> 印刷
		</a>
	</div>
	<div class="col-md-2 col-sm-6 col-xs-6">
		<button type="button" onclick="POLICY_DETAIL.goBack()" class="btn btn-space btn-warning col-md-12 col-sm-12 col-xs-12"><span class="icon-back"></span> 戻る</button>
	</div>
	<div class="col-md-2 col-sm-6 col-xs-6">
		<a href="/survey/vote/<?php echo $policy->getId()?>" 
			class="btn btn-space btn-warning col-md-12 col-sm-12 col-xs-12"> <span class="icon-survey"></span> アンケート入力</a>
	</div>
</div>
<div class="modal fade dialog-position" id="popupDialogSuccess" role="dialog">
	<div class="modal-dialog modal-sm">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		     	<h4 class="modal-title"><?php echo $this->translate('MSG_PO_004_TitleAddFavourite')?></h4>
		    </div>
			<div class="modal-body">
				<p id="vote_confirm"><?php echo $this->translate('MSG_PO_001_AddFavouriteSuccess')?> </p>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary btn-red" data-dismiss="modal" id="btnOkModal">完了</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade dialog-position" id="popupDialogStop" role="dialog">
	<div class="modal-dialog modal-sm">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		     	<h4 class="modal-title"><?php echo $this->translate('MSG_PO_006_LimitFavourite');?></h4>
		    </div>
			<div class="modal-body">
				<p id="vote_confirm"><?php echo $this->translate('MSG_PO_003_Max20Favourite')?></p>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary btn-red" data-dismiss="modal" id="btnOkModal">はい</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade dialog-position" id="popupDialogUnF" role="dialog">
	<div class="modal-dialog modal-sm">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		     	<h4 class="modal-title"><?php echo $this->translate('MSG_PO_005_TitleRemoveFavourite');?> </h4>
		    </div>
			<div class="modal-body">
				<p id="vote_confirm"><?php echo $this->translate('MSG_PO_002_RemoveFavouriteSuccess');?> </p>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary btn-red" data-dismiss="modal" id="btnOkModal">完了</button>
			</div>
		</div>
	</div>
</div>

<script
	type="text/javascript" src="<?php echo $this->basePath(); ?>/js/policy/policy-detail.js"></script>
<script>
    $(document).ready(function () {
    	POLICY_DETAIL.policyId = <?php echo json_encode($policy->getId())?>;
    	POLICY_DETAIL.userId = <?php echo json_encode($this->userInfo["userId"])?>;
    	POLICY_DETAIL.addFPolicy();
    });
    <?php if(isset($errorMsg)){?>
	    COMMON.errorPopup('<?php echo $errorMsg ?>');
	<?php } ?>
</script>
