<div class="container">
	<div class="col-md-offset-2 col-md-8 guideContent">
		<div class="col-md-offset-1 col-md-10">
			<div class="guideTitle">
				<h3>はじめての施策早わかりガイド</h3>
			</div>
			<div class="guidDescription">
				雇用の確保を図るため、推進しているさまざまな支援施策情報に関しては簡単に比較・一覧・出力できます。
			</div>
			<div>
				<ul>
					<li><a href="<?php echo $href['sitePolicy']; ?>">Site Policy</a></li>
					<li><a href="<?php echo $href['relatedLink']; ?>">Related Link</a></li>
					<li><a href="<?php echo $href['privacyPolicy']; ?>">Privacy Policy</a></li>
					<li><a href="<?php echo $href['inquiries']; ?>">Inquiries</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>