<div class="container">
	<div class="col-md-offset-2 col-md-8 guideContent">
		<div class="col-md-offset-1 col-md-10">
			<div class="guideTitle">
				<h3>Inquiries</h3>
			</div>
			<div class="guidDescription">
				<ol>
					<li>支援内容・分野・対象者・業種・支援額・事業（実施）期間の詳細などにチェックし、「検索」を押下します。支援内容・分野・対象者・業種・支援額・事業（実施）期間の詳細などにチェックし、「検索」を押下します。</li>
					<li>支援内容・分野・対象者・業種・支援額・事業（実施）期間の詳細などにチェックし、「検索」を押下します。支援内容・分野・対象者・業種・支援額・事業（実施）期間の詳細などにチェックし、「検索」を押下します。</li>
				</ol>
			</div>
		</div>
	</div>
</div>