<div class="container content-wrapper container-body">
    <div class="box-header"><?php echo $this->translate('MSG_MP_025_ActiveEmailTitlePage'); ?></div>
    <div class="panel-body">
        <div class="row">
            <div class="title"></div>
            <div class="col-sm-12">
                <form class="form-horizontal" method="post" id="forgot-form" >
                    <!--Error message content-->
                    <div class="form-group">
                        <div class="col-sm-12 col-xs-12 text-left flag-notice error-box" id="errors-list">
                            <?php if (!empty($errors)) { ?>
                                <ul>
                                    <?php foreach ($errors as $error) { ?>
                                        <li><h5><?php echo $error; ?></h5></li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <h5 class="col-sm-12 col-xs-12 control-label">
                            <?php echo $this->translate('MSG_MP_026_ActiveEmailMessage'); ?>
                        </h5>
                    </div>
                    <div class="form-group">
                        <label for="txtPassword" class="col-sm-4 col-xs-12"><?php echo $this->translate('MSG_LG_011_PasswordLabel'); ?></label>
                        <div class="col-sm-8 col-xs-12">
                            <input type="password" name="password" class="form-control" id="txtPassword">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-4 col-xs-12 pull-right">
                            <input type="submit" id="btnNext" name="btnNext"
                                   class="btn btn-success btn-space col-md-12 col-xs-12 col-sm-12"
                                   value="<?php echo $this->translate('MSG_AP_006_NextLabel') ?>" />
                        </div>
                        <div class="col-sm-4 col-xs-12 pull-right">
                            
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!--Scripts-->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/login/active-email.js"></script>
