<div class="container content-wrapper container-body">
    <div class="box-header"><?php echo $this->translate('MSG_LG_047_ChangeEmailSuccessTitle'); ?></div>
    <div class="panel-body">
        <div class="row">
            <div class="title"></div>
            <div class="col-sm-12">
                <form class="form-horizontal" method="post" id="forgot-form" >
                    <div class="form-group">
                        <h5 class="col-sm-12 col-xs-12 control-label">
                            <?php echo $this->translate('メールを正常に変更しました。ログインアカウントもメールと同じで変更されました。'); ?>
                            <br />
                            <br />
                            <a href="<?php echo $this->url('login'); ?>">ここ</a>をクリックし再ログインします。
                        </h5>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>