<div class="container content-wrapper container-body">
    <div class="box-header"><?php echo $this->translate('MSG_LG_011_PasswordLabel'); ?></div>
    <div class="panel-body">
        <div class="row">
            <div class="title"></div>
            <div class="col-sm-12">
                <form class="form-horizontal" id="submit-form" method="post"
                      action="">
                    <!--Error message content-->
                    <div class="form-group">
                        <div class="col-sm-12 col-xs-12 text-left flag-notice error-box" id="errors-list">
                            <?php if (!empty($errors)) { ?>
                                <ul>
                                    <?php foreach ($errors as $error) { ?>
                                        <li><h5><?php echo $error; ?></h5></li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="lbUserId"
                               class="col-sm-4 col-xs-12 control-label"><?php echo $this->translate('MSG_LG_037_IdLabel'); ?></label>
                        <div class="col-sm-8 col-xs-12">
                            <?php echo $username; ?>
                        </div>
                        <input type="hidden" name="username" value="<?php echo $username ?>" />
                    </div>
                    <div class="form-group">
                        <label for="txtOldPassword" class="col-sm-4 col-xs-12 control-label">旧パスワード</label>
                        <div class="col-sm-7 col-xs-12">
                            <input type="password" name="oldPassword" class="form-control" id="txtOldPassword"
                                   placeholder="旧パスワード">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtNewPassword"
                               class="col-sm-4 col-xs-12 control-label"><?php echo $this->translate('MSG_LG_038_NewPasswordLabel'); ?></label>
                        <div class="col-sm-7 col-xs-12">
                            <input type="password" class="form-control" id="txtNewPassword"
                                   name="newPassword"
                                   placeholder="<?php echo $this->translate('MSG_LG_038_NewPasswordLabel'); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtConfirmPassword"
                               class="col-sm-4 col-xs-12 control-label"><?php echo $this->translate('MSG_LG_039_ConfirmNewPasswordLabel'); ?></label>
                        <div class="col-sm-7 col-xs-12">
                            <input type="password" class="form-control" id="txtConfirmPassword"
                                   name="confirmPassword"
                                   placeholder="<?php echo $this->translate('MSG_LG_039_ConfirmNewPasswordLabel'); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-4 col-xs-offset-0 col-md-7 col-xs-12">
                            <input type="submit" name="btnSubmit" id="btnSubmit"
                                   class="btn btn-success btn-space col-sm-5 col-xs-12 pull-right"
                                   value="<?php echo $this->translate('MSG_AP_007_ConfirmLabel') ?>">
                            </input>
                            <a id="btnBack" href="<?php echo $this->url('login/role', array('role' => $ref)); ?>"
                               class="btn btn-default btn-space col-sm-5 col-xs-12 pull-left"><?php echo $this->translate('MSG_AP_005_BackLabel') ?>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!--Success modal-->
<div class="modal fade dialog-position" id="confirm-success-dialog" role="dialog" data-keyboard="false"
     data-backdrop="static">
    <div class="modal-dialog modal-sm">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?php echo $this->translate('MSG_LG_040_UpdatePassSuccessLabel') ?></h4>
            </div>
            <div class="modal-body text-left">
                <?php echo $this->translate('MSG_LG_041_UpdatePassSuccessMessage') ?>
            </div>
            <div class="modal-footer">
                <div class="col-sm-12 col-xs-12 text-left">
                    <a id="btnFinish" href="<?php echo $this->url('login/role', array('role' => $ref)); ?>"
                       class="btn btn-primary col-sm-5 col-xs-5 pull-right"><?php echo $this->translate('MSG_AP_004_FinishLabel'); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Scripts-->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/login/new-password.js"></script>

<script>
    $(document).ready(function () {
        NEW_PASSWORD.messageList = <?php echo json_encode($translator); ?>;
        NEW_PASSWORD.init();
    });
</script>
