<div class="container content-wrapper container-body">
    <div class="box-header"><?php echo $this->translate('MSG_LG_015_ForgotPasswordTitle'); ?></div>
    <div class="panel-body">
        <div class="row">
            <div class="title"></div>
            <div class="col-sm-12">
                <form class="form-horizontal" method="post" id="forgot-form"
                      action="<?php echo empty($ref) ? '' : "?ref=$ref" ?>">
                    <!--Error message content-->
                    <div class="form-group">
                        <div class="col-sm-12 col-xs-12 text-left flag-notice error-box" id="errors-list">
                            <?php if (!empty($errors)) { ?>
                                <ul>
                                    <?php foreach ($errors as $error) { ?>
                                        <li><h5><?php echo $error; ?></h5></li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <h5 class="col-sm-12 col-xs-12 control-label">
                            <?php echo $this->translate('MSG_LG_034_ForgotPasswordMessage'); ?>
                        </h5>
                    </div>
                    <div class="form-group">
                        <label for="txtUsername"
                               class="col-sm-4 col-xs-12"><?php echo $this->translate('MSG_LG_010_UserIdLabel'); ?></label>
                        <div class="col-sm-8 col-xs-12">
                            <input type="text" name="username" class="form-control" id="txtUsername"
                                <?php echo empty($username) ? '' : 'value="' . $this->escapeHtml($username) . '"' ?>
                                   placeholder="<?php echo $this->translate('MSG_LG_010_UserIdLabel'); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cbMailFlag" class="col-sm-4 col-xs-12 control-label"></label>
                        <div class="col-sm-8 col-xs-12">
                            <label class="form-check-input">
                                <input id="cbMailFlag" onchange="FORGOT_PASSWORD.onMailExist(this)" type="checkbox" name="mailFlag"
                                       value="1" <?php echo empty($mailFlag) ? '' : 'checked' ?> />
                                <label for="cbMailFlag"></label>
                                <?php echo $this->translate('MSG_LG_035_PeopleNotEmailLabel'); ?>
                            </label>
                        </div>
                    </div>
                    <div id="question-form" class="form-horizontal"
                         style="<?php echo !empty($mailFlag) ? '' : 'display: none' ?>">
                        <div class="form-group">
                            <label for="ddlQuestion"
                                   class="col-sm-4 col-xs-12 control-label"><?php echo $this->translate('MSG_LG_031_SecurityQuestionLabel'); ?></label>
                            <div class="col-sm-8 col-xs-12">
                                <select class="form-control" id="ddlQuestion" name="questionId">
                                    <?php foreach ($questions as $question) { ?>
                                        <option <?php echo empty($questionId) ? '' : (($questionId == $question['id']) ? 'selected' : '') ?>
                                                value="<?php echo $question['id']; ?>"><?php echo $question['content']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="txtAnswer"
                                   class="col-sm-4 col-xs-12 control-label"><?php echo $this->translate('MSG_LG_036_AnswerLabel'); ?></label>
                            <div class="col-sm-8 col-xs-12">
                                <input type="text" name="answer" class="form-control" id="txtAnswer"
                                    <?php echo empty($answer) ? '' : 'value="' . $this->escapeHtml($answer) . '"'; ?>
                                       placeholder="<?php echo $this->translate('MSG_LG_036_AnswerLabel'); ?>" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-4 col-xs-12 pull-right">
                            <input type="submit" id="btnNext" name="btnNext"
                                   class="btn btn-success btn-space col-md-12 col-xs-12 col-sm-12"
                                   value="<?php echo $this->translate('MSG_AP_006_NextLabel') ?>" />
                        </div>
                        <div class="col-sm-4 col-xs-12 pull-right">
                            <a id="btnBack" href="<?php echo $this->url('login/role', array('role' => $ref)); ?>"
                               class="btn btn-default btn-space col-md-12 col-xs-12 col-sm-12"><?php echo $this->translate('MSG_AP_005_BackLabel') ?>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!--Scripts-->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/login/forgot-password.js"></script>

<script>
    $(document).ready(function () {
        FORGOT_PASSWORD.messageList = <?php echo json_encode($translator) ?>;
        FORGOT_PASSWORD.init();
        FORGOT_PASSWORD.preLoad();
    });

</script>