<div class="container content-wrapper container-body">
    <div class="box-header"><?php echo $this->translate('MSG_LG_044_RegisterSecurityQuestionTitle'); ?></div>
    <div class="panel-body">
        <div class="row">
            <div class="title"></div>
            <div class="col-sm-12">
                <form class="form-horizontal" id="submit-form" method="post"
                      action="<?php echo empty($ref) ? '' : "?ref=$ref"; ?>">
                    <!--Error message content-->
                    <div class="form-group">
                        <div class="col-sm-12 col-xs-12 text-left flag-notice error-box" id="errors-list">
                            <?php if (!empty($errors)) { ?>
                                <ul>
                                    <?php foreach ($errors as $error) { ?>
                                        <li><h5><?php echo $error; ?></h5></li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                    </div>
                    <input type="hidden" name="username" value="<?php echo $username ?>" />
                    <input type="hidden" name="password" value="<?php echo $password ?>" />
                    <div class="form-group">
                        <label for="ddlQuestionId"
                               class="col-sm-4 col-xs-12 control-label"><?php echo $this->translate('MSG_LG_031_SecurityQuestionLabel') ?></label>
                        <div class="col-sm-8 col-xs-12">
                            <select class="form-control" name="questionId"
                                    id="ddlQuestionId">
                                <?php foreach ($questions as $question) { ?>
                                    <option <?php echo !empty($questionId) && $question['id'] == $questionId ? 'selected' : '' ?>
                                            value="<?php echo $question['id']; ?>"><?php echo $question['content']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtAnswer"
                               class="col-sm-4 col-xs-12 control-label"><?php echo $this->translate('MSG_LG_036_AnswerLabel') ?></label>
                        <div class="col-sm-8 col-xs-12">
                            <input type="text" class="form-control" id="txtAnswer"
                                   value="<?php echo !empty($answer) ? $this->escapeHtml($answer) : '' ?>"
                                   placeholder="<?php echo $this->translate('MSG_LG_036_AnswerLabel') ?>"
                                   name="answer">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-4 col-xs-offset-0 col-sm-8 col-xs-12 ">
                            <input type="submit" name="btnSubmit" id="btnSubmit"
                                   class="btn btn-success btn-space col-sm-5 col-xs-12 pull-right"
                                   value="<?php echo $this->translate('MSG_AP_008_RegisterLabel') ?>" />
                            </input>
                            <a id="btnBack" href="<?php echo $this->url('login/role', array('role' => $ref)) ?>"
                               class="btn btn-default btn-space col-sm-5 col-xs-12 pull-left"><?php echo $this->translate('MSG_AP_005_BackLabel') ?>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!--Scripts-->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/login/security-question.js"></script>

<script>
    $(document).ready(function () {
        SECURITY_QUESTION.messageList = <?php echo json_encode($translator);?>;
        SECURITY_QUESTION.init();
    });
</script>