<div id="changePasswordModal" class="modal fade dialog-position" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">パスワード</h4>
            </div>
            <div class="modal-body">
                <div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="title"></div>
                            <div class="col-sm-12">
                                <form id="frmChangePassword" class="form-horizontal" action="<?php echo $this->url('my-page/default', array('action' => 'change-password')); ?>">
                                    <div class="form-group">
                                        <div class="col-sm-12 col-xs-12 text-left flag-notice" id="errors-list-change-password">
                                            
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 col-xs-12 control-label">ID</label>
                                        <div class="col-sm-7 col-xs-12">
                                            <h5><?php if(isset($userInfo['username'])) echo $userInfo['username'];?></h5>
                                        </div>
                                        <input type="hidden" name="userId" value="<?php echo $this->userInfo['userId'];?>" />
                                    </div>
                                                                        
                                    <div class="form-group">
                                        <label class="col-sm-4 col-xs-12 control-label">旧パスワード</label>
                                        <div class="col-sm-7 col-xs-12">
                                            <input type="password" class="form-control" id="oldPassword" name="oldPassword" required placeholder="旧パスワード" />
                                            <label class="error" id="oldPassword-error" style="display: none;" for="oldPassword"></label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 col-xs-12 control-label">新しいパスワード</label>
                                        <div class="col-sm-7 col-xs-12">
                                            <input type="password" class="form-control" id="newPassword" name="newPassword" required placeholder="新しいパスワード">
                                            <label class="error" id="newPassword-error" style="display: none;" for="newPassword"></label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 col-xs-12 control-label">
                                            新しいパスワード <br />（確認）
                                        </label>
                                        <div class="col-sm-7 col-xs-12">
                                            <input type="password" class="form-control" id="newPasswordRetype" name="newPasswordRetype" required placeholder="新しいパスワード（確認）">
                                            <label class="error" id="newPasswordRetype-error" style="display: none;" for="newPasswordRetype"></label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-4 col-xs-offset-0 col-sm-7 col-xs-12 ">
                                            <button type="button" onclick="closeChangePassword();" class="btn btn-default col-sm-5 col-xs-5 pull-left">戻る</button>
                                            <button type="submit" class="btn btn-primary col-sm-5 col-xs-5 pull-right">確認</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade dialog-position" id="successChangePasswordModal" role="dialog">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">パスワードの変更完了</h4>
            </div>
            <div class="modal-body text-left">
                <span>パスワード変更が完了しました。<br/>
                次回からは新しいパスワードでログインしてください。</span>
            </div>
            <div class="modal-footer">
                <div class="col-sm-12 col-xs-12 text-right">
                    <button type="button" onclick="closeSuccessChangePasswordModal()" class="btn btn-primary col-sm-5 col-xs-5 pull-right">完了</button>
                </div>
            </div>
        </div>

    </div>
</div>

<script>
$(function(){
    CHANGE_PASSWORD.init();
    
    $('#changePasswordModal').on('show.bs.modal', function() {
        $("#oldPassword").val("");
        $("#newPassword").val("");
        $("#newPasswordRetype").val("");
        
        $("#oldPassword").removeClass('error');
        $("#newPassword").removeClass('error');
        $("#newPasswordRetype").removeClass('error');
        
        setTimeout(function(){
            if(navigator.appVersion.indexOf("MSIE 9.") !== -1) {
                $('#changePasswordModal input').placeholder();
            }
            $('#oldPassword').focus();
        }, 10);
        
        CHANGE_PASSWORD.validateForm.resetForm();
    });
});

function closeChangePassword(){
    $('#changePasswordModal').modal('hide');
    $('#infoUserModal').modal({backdrop: 'static'});
}

function closeSuccessChangePasswordModal(){
    $('#successChangePasswordModal').modal('hide');
    location.reload();    
}
</script>