<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>【産労AP】</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- Le styles -->
    <link href="<?php $this->basePath(); ?>/css/jquery-ui.css" media="screen,print" rel="stylesheet" type="text/css">
    <link href="<?php $this->basePath(); ?>/css/bootstrap.min.css" media="screen,print" rel="stylesheet"
          type="text/css">
    <link href="<?php $this->basePath(); ?>/css/bootstrap-theme.min.css" media="screen,print" rel="stylesheet"
          type="text/css">
    <link href="<?php $this->basePath(); ?>/css/styleLogin.css" media="screen,print" rel="stylesheet" type="text/css">
    <link href="<?php $this->basePath(); ?>/css/styleTable.css" media="screen,print" rel="stylesheet" type="text/css">
    <link href="<?php $this->basePath(); ?>/css/styleLayout.css" media="screen,print" rel="stylesheet" type="text/css">
    <link href="<?php $this->basePath(); ?>/css/style.css" media="screen,print" rel="stylesheet" type="text/css">
    <link href="<?php $this->basePath(); ?>/css/print.css" media="screen,print" rel="stylesheet" type="text/css">
    <link href="<?php $this->basePath(); ?>/css/bootstrap-datetimepicker.css" media="screen,print" rel="stylesheet"
          type="text/css">
    <link href="<?php $this->basePath(); ?>/css/bootstrap-datepicker.css" media="screen,print" rel="stylesheet"
          type="text/css">

    <!-- Scripts -->
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/jquery-ui.js"></script>
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/jquery-validation/jquery.validate.js"></script>
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/jquery-validation/additional-methods.js"></script>
    <!--[if IE]>
        <script type="text/javascript" src="<?php $this->basePath(); ?>/js/jquery-placeholder/jquery.placeholder.js"></script>
    <![endif]-->
    <script type="text/javascript" src="<?php $this->basePath(); ?>/js/common.js"></script>
    <!--[if IE]>
    <style>
        input, textarea { color: #000; }
        .placeholder { color: #aaa; }
    </style>
    <![endif]-->
</head>
<body>
<div class="container-fluid">
    <!--Page Header-->
    <nav class="bg-primary header-layout-on">
        <div class="container header-layout-on">
            <div class="row">
                <div class="navbar-header col-md-12 col-sm-12 text-center ">
                        <img src="/images/logo.jpg" class="logo">
                </div>
            </div>
            <!-- ID LOGO END-->

            <!--</div>&lt;!&ndash; /.container-fluid &ndash;&gt;-->
        </div><!-- /.container-fluid -->
    </nav>
    <!--End page header-->

    <!--Page body-->
    <div class="container">
        <?php echo $this->content; ?>
    </div>
    <!--End page body-->
    <!--Page footer-->
    <footer class="text-center footer">
        <p class="text-color-white">Copyright© 2017 Bureau of Industrial and Labor Affairs, Tokyo Metropolitan Government. All Rights Reserved.</p>
    </footer>
    <script>
        $( window ).resize(function() {
            changeWindowSize();
        });
        function changeWindowSize() {
            var heightWindow = $(window).height();
            var heightFooterMenu = $('.footer-menu').height();
            var headerLayoutOn = $('.container-fluid>.header-layout-on').height();
            var heightFooter = $('.footer').height();
            var heightLayoutUp = $('.container-fluid>.header-layout-up').height();
            var heightContent = $('.container-fluid>.container').height();

//            if(heightWindow>(heightFooterMenu+headerLayoutOn+heightFooter+heightLayoutUp+heightContent))
//            {
                $('.container-fluid>.container').css("min-height", heightWindow-headerLayoutOn-heightFooter-heightFooterMenu-heightLayoutUp-10);

//            }

        }
        $(document).ready(function () {
            changeWindowSize();
        });

    </script>
    <!--End page footer-->
    
    <div id="full-screen" class="full-screen" style="display: none;"></div>
</div>
</body>
</html>
