<div class="container">
    <div class="container content-medium-wrapper container-body">
        <div class="box-header">
            <?php echo $this->translate('MSG_NO_001_NoticeNormal'); ?>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="title"></div>
                <div id="surveyNotice" class="col-sm-12">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label for="input" class="col-sm-12 col-xs-12 text-left">
                                <?=$noticeInfo['description'];?>
                            </label>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 text-right">
                <div class="col-sm-2 col-xs-12 pull-right">
                    <button type="button" class="btn btn-space btn-default col-sm-12 col-xs-12"onclick="NOTICE.closeNoticeWindow()" data-dismiss="modal"><?php echo $this->translate('MSG_AP_005_BackLabel'); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/notice/notice.js"></script>
