<!--Scripts-->

<!--Body-->
<?php
use Application\Utils\UserHelper;
?>
<div class="container content-wrapper container-body">
    <div class="box-header">
        <div class="row">
            <div class="col-md-8 col-sm-8 col-xs-12"> <h4>
                    <b>
                        <?php
                        if(isset($this->roleId) && UserHelper::isAdministrator($this->roleId))
                            echo $this->translate('title_menu_system');
                        if(isset($this->roleId) && UserHelper::isInputRole($this->roleId))
                            echo $this->translate('title_menu_input');
                        ?>
                    </b></h4></div>
            <div class="col-md-4 col-sm-4 pull-right text-right   ">
                <?php
                if(isset($this->roleId) && UserHelper::isInputRole($this->roleId)) {
                    ?>
                    <a href="/viewer/guide/index">
                        <h5>
                            ？使い方ガイド
                        </h5>
                    </a>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
    <?php
        $label_menu_policy = "";    
        $label_menu_homepage = ""; 
        if(isset($this->roleId) && UserHelper::isAdministrator($this->roleId)){
            $label_menu_policy = $this->translate('label_system_menu_policy');   
            $label_menu_homepage = $this->translate('label_system_menu_homepage');   
            $url = $this->url('administrator/default', array('controller' => 'menu', 'action'=>'main-management'));
        }
        
        if(isset($this->roleId) && UserHelper::isInputRole($this->roleId)){
            $label_menu_policy = $this->translate('label_input_menu_policy');
            $label_menu_homepage = $this->translate('label_input_menu_homepage');
            $url = $this->url('administrator/default', array('controller' => 'policy-management'));    
        }   
    ?>
    
    <div class="panel-body">
        <div class="row">
            <div class="title"></div>
            <div class="col-sm-12">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-12 col-xs-12 control-label"><?php echo $label_menu_policy;?></label>
                        <div class="col-sm-12 col-xs-12">
                            <a href="<?php echo $url;?>" class="btn btn-primary col-sm-12 col-xs-12">
                                <?php echo $label_menu_policy;?>
                            </a>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-12 col-xs-12 control-label"><?php echo $label_menu_homepage;?></label>
                        <div class="col-sm-12 col-xs-12">
                            <a href="/" class="btn btn-primary col-sm-12 col-xs-12"><?php echo $label_menu_homepage;?></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>