<div class="row">
    <div class="col-sm-12">
        <div class="row ">
            <a class="pull-left col-md-2" href="home-module-guide-main.html">？使い方ガイド</a>
            <div class="col-md-2 pull-right" style="padding-left: 5px">
                <button data-toggle="modal" data-target="#searchConditionCall" type="button" class="btn btn-info col-md-12" data-color="primary">検索条件呼び出し</button>
            </div>
        </div>

        <form>
            <table id="table2" class="table tab-content table-bordered">
                <tbody>
                    <tr>
                        <td class="thread-vertical col-sm-2">フリーワード検索</td>
                        <td>
                            <input class="form-control" placeholder="キーワードを入力してください" >
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="row">
                <div class="col-md-12 text-center">
                    <button type="button" id="boxSearch1" class="search-toggle-btn">
                        <span>細かい条件を指定する</span>
                    </button>
                </div>
            </div>
            <table id="detailSearch1" style="display: none" class="table tab-content table-bordered">
                <tbody>
                    <tr>
                        <td class="thread-vertical col-sm-2">支援内容</td>
                        <td id="groupA">
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-A1" type="checkbox" name="rowa1" /> 補助金・助成金
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-A2" type="checkbox" name="rowa1" /> 融資制度専門家によるコンサルティング
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-A3" type="checkbox" name="rowa1" /> セミナー・研修
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-A4" type="checkbox" name="rowa1" /> 事業者募集
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-A5" type="checkbox" name="rowa1" /> その他
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 col-sm-offset-6">
                                    <button name="selectAll" onclick="checkAllRow(this)" type="button" class="btn btn-info" data-color="primary"><i class="state-icon glyphicon glyphicon-check"></i><b>&nbsp;全選択</b></button>
                                </div>
                                <div class="col-md-3">
                                    <button name="unSelectAll" onclick="uncheckAllRow(this)" type="button" class="btn btn-default" data-color="primary"><i class="state-icon glyphicon glyphicon-unchecked"></i>&nbsp;全解除</button>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="thread-vertical col-sm-2">分野</td>
                        <td>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-B1" type="checkbox" name="rowb1" /> 創業・起業　
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-B2" type="checkbox" name="rowb1" /> 研究開発／商品・サービス開発
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-B3" type="checkbox" name="rowb1" /> 販路開拓
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-B4" type="checkbox" name="rowb1" /> 海外展開
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-B5" type="checkbox" name="rowb1" /> 事業承継・事業再生
                                    </label>
                                </div>
                                <div class="col-md-3 ">
                                    <label class="form-check-input">
                                        <input id="id-B6" type="checkbox" name="rowb1" /> 人材確保　
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-B7" type="checkbox" name="rowb1" /> 雇用環境整備
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-B8" type="checkbox" name="rowb1" /> 人材育成
                                    </label>
                                </div>
                                <div class="col-md-3 ">
                                    <label class="form-check-input">
                                        <input id="id-B9" type="checkbox" name="rowb1" /> 設備投資　
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-B10" type="checkbox" name="rowb1" /> 知的財産
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-B11" type="checkbox" name="rowb1" /> エネルギー・環境
                                    </label>
                                </div>
                                <div class="col-md-3 ">
                                    <label class="form-check-input">
                                        <input id="id-B12" type="checkbox" name="rowb1" /> 健康・医療　
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-B13" type="checkbox" name="rowb1" /> 観光
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-B14" type="checkbox" name="rowb1" /> その他
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 col-sm-offset-6">
                                    <button name="selectAll" onclick="checkAllRow(this)" type="button" class="btn btn-info" data-color="primary"><i class="state-icon glyphicon glyphicon-check"></i><b>&nbsp;全選択</b></button>
                                </div>
                                <div class="col-md-3">
                                    <button name="unSelectAll" onclick="uncheckAllRow(this)" type="button" class="btn btn-default" data-color="primary"><i class="state-icon glyphicon glyphicon-unchecked"></i>&nbsp;全解除</button>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>

        </form>

        <div class="row">
            <div class="col-md-12 text-center" >
                <button type="button" id="boxSearch2" class="search-toggle-btn" style="display: none;">
                    <span>さらに細かい条件を指定する</span>
                </button>
            </div>
        </div>
        <form>
            <table id="detailSearch2" class="table tab-content table-bordered" style="display: none">
                <tbody>
                    <tr>
                        <td class="thread-vertical col-sm-2">対象地域</td>
                        <td>
                            <div class="row col-sm-4">
                                <select class="form-control ">
                                    <option>東京都外も含む</option>
                                    <option>東京都内</option>
                                </select>

                            </div>

                        </td>
                    </tr>
                    <tr>
                        <td class="thread-vertical col-sm-2">対象者</td>
                        <td>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-C1" type="checkbox" name="rowc1" /> 大企業
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-C2" type="checkbox" name="rowc1" /> 中小企業者
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-C3" type="checkbox" name="rowc1" /> 小規模事業者
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-C5" type="checkbox" name="rowc1" /> 個人事業者
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-C4" type="checkbox" name="rowc1" /> NPO 法人(特定非営利活動法人)
                                    </label>
                                </div>

                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-C6" type="checkbox" name="rowc1" /> その他
                                    </label>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-3 col-md-offset-6 ">
                                    <button id="id-C-All" name="selectAll" onclick="checkAllRow(this)" type="button" class="btn btn-info" data-color="primary"><i class="state-icon glyphicon glyphicon-check"></i><b>&nbsp;全選択</b></button>
                                </div>
                                <div class="col-md-3">
                                    <button id="id-C-unAll" name="unSelectAll" onclick="uncheckAllRow(this)" type="button" class="btn btn-default" data-color="primary"><i class="state-icon glyphicon glyphicon-unchecked"></i>&nbsp;全解除</button>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="thread-vertical col-sm-2">対象業種</td>
                        <td>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D1" type="checkbox" name="rowd1" /> 製造業
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D2" type="checkbox" name="rowd1" /> サービス業
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D3" type="checkbox" name="rowd1" /> 卸売・小売業
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D4" type="checkbox" name="rowd1" /> 情報通信業
                                    </label>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D5" type="checkbox" name="rowd1" /> 農林水産業
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D6" type="checkbox" name="rowd1" /> 運輸業
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D7" type="checkbox" name="rowd1" /> 建設・不動産業
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D8" type="checkbox" name="rowd1" /> 医療・福祉
                                    </label>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-D9" type="checkbox" name="rowd1" /> その他
                                    </label>
                                </div>
                                <div class="col-md-3 col-md-offset-3 ">
                                    <button id="id-D-All" name="selectAll" onclick="checkAllRow(this)" type="button" class="btn btn-info" data-color="primary"><i class="state-icon glyphicon glyphicon-check"></i><b>&nbsp;全選択</b></button>
                                </div>
                                <div class="col-md-3">
                                    <button id="id-D-unAll" name="unSelectAll" onclick="uncheckAllRow(this)" type="button" class="btn btn-default" data-color="primary"><i class="state-icon glyphicon glyphicon-unchecked"></i>&nbsp;全解除</button>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="thread-vertical col-sm-2">支援額</td>
                        <td>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E1" type="checkbox" name="rowe1" /> 100 万円以下
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E2" type="checkbox" name="rowe1" /> 100 万〜500 万円以下
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E3" type="checkbox" name="rowe1" /> 500 万〜1000 万円以下　
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E4" type="checkbox" name="rowe1" /> 1000 万〜5000 万円以下
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E5" type="checkbox" name="rowe1" /> 5000万円以上
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E5" type="checkbox" name="rowe1" /> 該当なし　
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 col-sm-offset-6">
                                    <button id="id-E-All" name="selectAll" onclick="checkAllRow(this)" type="button" class="btn btn-info" data-color="primary"><i class="state-icon glyphicon glyphicon-check"></i><b>&nbsp;全選択</b></button>
                                </div>
                                <div class="col-md-3">
                                    <button id="id-E-unAll" name="unSelectAll" onclick="uncheckAllRow(this)" type="button" class="btn btn-default" data-color="primary"><i class="state-icon glyphicon glyphicon-unchecked"></i>&nbsp;全解除</button>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="thread-vertical col-sm-2">支援対象者数</td>
                        <td>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E5" type="checkbox" name="rowe1" /> 1～50
                                    </label>
                                </div>
                                <div class="col-md-3 ">
                                    <label class="form-check-input">
                                        <input id="id-E5" type="checkbox" name="rowe1" /> 51～100
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E5" type="checkbox" name="rowe1" /> 101～200
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-E5" type="checkbox" name="rowe1" /> 200以上
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="form-check-input">
                                        <input id="id-E5" type="checkbox" name="rowe1" /> 該当なし
                                    </label>
                                </div>
                                <div class="col-md-3 ">
                                    <button id="id-E-All" name="selectAll" onclick="checkAllRow(this)" type="button" class="btn btn-info" data-color="primary"><i class="state-icon glyphicon glyphicon-check"></i><b>&nbsp;全選択</b></button>
                                </div>
                                <div class="col-md-3">
                                    <button id="id-E-unAll" name="unSelectAll" onclick="uncheckAllRow(this)" type="button" class="btn btn-default" data-color="primary"><i class="state-icon glyphicon glyphicon-unchecked"></i>&nbsp;全解除</button>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                        <td class="thread-vertical col-sm-2">募集(実施)期間</td>
                        <td>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-F1" type="checkbox" name="rowf1" /> 募集中
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-F2" type="checkbox" name="rowf1" /> 募集前
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-F3" type="checkbox" name="rowf1" /> 受付終了
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-check-input">
                                        <input id="id-F4" type="checkbox" name="rowf1" /> その他
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 col-md-offset-6">
                                    <button id="id-F-All" name="selectAll" onclick="checkAllRow(this)" type="button" class="btn btn-info" data-color="primary"><i class="state-icon glyphicon glyphicon-check"></i><b>&nbsp;全選択</b></button>
                                </div>
                                <div class="col-md-3">
                                    <button id="id-F-unAll" name="unSelectAll" onclick="uncheckAllRow(this)" type="button" class="btn btn-default" data-color="primary"><i class="state-icon glyphicon glyphicon-unchecked"></i>&nbsp;全解除</button>
                                </div>
                            </div>
                        </td>

                    </tr>

                </tbody>
            </table>
        </form>
        <div class="row">
            <div class="col-md-12 text-center">
                <button type="button" class="btn btn-info col-md-4 col-md-offset-4"><span class="text-color-white">検索</span></button>
                <div class="col-sm-2 pull-right" style="padding-right: 0">
                    <button id="saveCondition" data-toggle="modal" data-target="#policySave" type="button" class="btn btn-info col-md-12 pull-right" data-color="primary">検索条件の保存</button>
                </div>
            </div>
        </div>
        <div class="heighthr"></div>
    </div>
</div>

<div class="row" style=" margin-top: 20px;">
    <div class="col-md-12">
        <div class="col-sm-2 pull-left" style="padding-left: 0">
            <button type="button" class="btn btn-space btn-info btnFavorites col-md-12"><span>お気に入り施策の登録</span></button>
        </div>
                            <!--<button type="button" id="btnSettingMail" onclick="onMailSettingOpition()" class="btn btn-info btnInformMail col-md-2"><span>メール通知設定</span></button>-->
        <div class="col-sm-2 pull-right" style="padding-right: 0">
            <button type="button" class="btn col-md-12 btn-info pull-right" onclick="checkExistRow('選択項目にチェックを入れてください', '<?php $this->basePath(); ?>/file/policy_comparison.xlsx')" >施策比較表作成</button>
        </div>
    </div>
</div>
<div class="row" >
    <div class="col-sm-12 col-xs-12 border-box ">
        <div class="box-data">
            <div class="row">
                <div class="col-sm-2" style="padding-left: 0">
                    <button type="button" class="btn col-md-12 btn-primary btnPolicyTab">新着順</button>
                </div>
                <div class="col-sm-2">
                    <button type="button" class="btn col-md-12 btn-info btnPolicyTab" >アクセス数順</button>
                </div>
                <div class="col-sm-2">
                    <button type="button" class="btn col-md-12 btn-info btnPolicyTab">もうすぐ締切順</button>
                </div>
                <div class="col-sm-2">
                    <button id="btnFavoritePolicy" type="button" class="btn btn-space col-md-12 btn-info  btnPolicyTab">お気に入り施策</button>
                </div>
                <div class="col-sm-2">
                    <button type="button" class="btn btn-space btn-info col-md-12 btnPolicyTab">最近チェックした施策</button>
                </div>
                <div class="col-sm-2" style="padding-right: 0">
                    <button id="btnInformMail" type="button" class="btn btn-space btn-info col-md-12 btnPolicyTab">メール通知設定施策</button>
                </div>

            </div>
            <div class="row">
                <table id="table1" class="table tab-content table-bordered table-striped table-hover header-fixed">
                    <thead>
                        <tr>
                            <th class="text-center">
                                <input onchange="checkAll(this)" type="checkbox" value="" />
                            </th>
                            <th>
                            </th>
                            <th class="text-center" style="width: 28%">施策名</th>
                            <th class="text-center">施策内容</th>
                            <th class="text-center "style="width: 13%;">募集(実施)期間 </th>
                            <th class="text-center" style="width: 6%">チラシ</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">1</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    革新的ものづくり商業サービス開発ビス開発発り商業サービス開発ビスり
                                </a>
                            </td>
                            <td>融資限度額：①1億円、②3千万円、③1千万円
                                資金使途　：運転資金、設備資金
                                融資利率　：金融機関所定利率-0.3%
                                融資期間　：①運転資金10年以内（うち据置期間2年以内）、
                                </a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">2</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    革新的ものづくり商業サービス開発ビス開発発り商業サービス開発ビスり商業サービス革新的ものづくり商業サービス開発ビス開発発り商業サービス開発ビスり商業サービス革新的ものづくり商業サービス開発ビス開発発り「。。。」
                                </a>
                            </td>
                            <td>元的に集約した情報ボタ・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的元的に集約した情報ボタ・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的元的に集約した情報ボタ・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的革新的「。。。」</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">3</td>

                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    革新的ものづくり商業サービス開発ビス開発発り商業サー
                                </a>

                            </td>
                            <td>元的に集約した情報ボタ・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的元的に集約した情報ボタ・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的元的に集約した情報ボタ・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的革新的「。。。」</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">4</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    小さな会社が成長し世界を目指すようになるまで ～失敗や苦労越えた先に
                                </a>
                            </td>
                            <td>等を契機入社・報イト革新的ものづくり・商業・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">5</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    革新的ものづくり商業サービス開発ビス開発発り商業サービス開発ビスり商業サービス革新的ものづくり商業サービス開発ビス開発発り商業サービス開発ビスり商業サービス革新的ものづくり商業サービス開発ビス開発発り「。。。」
                                </a>
                            </td>
                            <td>等をを一元的に集約したタールものづくり・商業・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">6</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    岩手県小規模小口資金　利子補給補助金・保証料補給補助金<span class="flag-notice">【お気に入り】</span>
                                </a>
                            </td>
                            <td>等を契機とするを一元ボタト革新的くり・商業・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">7</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    空き店舗入居支援補助<span class="flag-notice">【お気に入り】</span>
                                </a>
                            </td>
                            <td>等を契機集約した情報サイト革新的ものづくり・商業・サービス開発支援補助金革新的ものづくり・商業・サービス開発支援補助金革新的</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">8</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    革新的ものづくり・商業・サービス開発
                                </a>
                            </td>
                            <td>等を契機民を一元的に集ルサイト革新的ものづくり・商業・サービス開発金革新的ものづくり・商業・サービス開発支援補助金革新的</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">9</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    革新的ものづくり・商業・サービス開発
                                </a>
                            </td>
                            <td>の入社・調達情報を一元タールサイト革新的ものづくり・商業・サービス助金革新的ものづくり・商業・サービス開発支援補助金革新的</a></td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="rowTab1[]" value="" />
                            </td>
                            <td class="text-center">10</td>
                            <td>
                                <a href="home-module-2-3-policy-detail.html">
                                    革新的ものづくり・商業・サービス開発
                                </a>
                            </td>
                            <td>等を契機と情報ボタールサイト革新的ものづくり・商業・サービス開金革新的ものづくり・商業・サービス開発支援補助金革新的</td>
                            <td>平成２9年3月4日～ 平成２9年４月25日</td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a target="_blank" href="../ランチ.pdf" class="dropdown-toggle" data-toggle="dropdown" ><img src="<?php $this->basePath(); ?>/images/paper.png" height="20" width="20" alt="ランチ.pdf" title="" /></a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_1.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_1.pdf</a></li>
                                        <li><a href="<?php $this->basePath(); ?>/file/ランチ_2.pdf" target="_blank"><img src="<?php $this->basePath(); ?>/images/oficina_pdf.png" height="20" width="20" alt="ランチ.pdf" title="ランチ.pdf" />ランチ_2.pdf</a></li>
                                        <li class="text-right"><a href="<?php $this->basePath(); ?>/file/ランチ.zip" class="text-color-blue">すべてをダウンロード</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="row">
                <nav class="text-center">
                    <div class="row">総件数〇〇件&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;〇件から〇件を表示</div>
                    <ul class="pagination">
                        <li><a href="#">&lt;&lt;</a></li><li><a href="#">&lt;</a></li><li class="active"><a href="#">1</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li><a href="#">4</a></li><li><a href="#">5</a></li><li><a href="#">&gt;</a></li><li><a href="#">&gt;&gt;</a></li>                        </ul>
                </nav>
            </div>
            <div class="row heighthr "></div>
            <div class="row">
                <!--<div class="pull-left ">
                    <button type="button" class="btn btn-space btn-info btnFavorites col-md-2"><span>お気に入り施策の登録</span></button>
                                                    <button type="button" class="btn btn-info btnInformMail col-md-2"><span>メール通知設定</span></button>
                </div>
                <div class="col-md-6 pull-right">
                    <button type="button" onclick="checkExistRow('選択項目にチェックを入れてください','home-module-2-4-confirm-print-policy.html')" class="btn  btn-info pull-right">施策比較表作成</button>
                </div>-->
                <div class="col-md-12">
                    <button type="button" class="btn btn-space btn-info btnFavorites col-md-2"><span>お気に入り施策の登録</span></button>
                    <!--<button type="button" onclick="onMailSettingOpition()" class="btn btn-info btnInformMail col-md-2"><span>メール通知設定</span></button>-->
                    <button type="button" onclick="checkExistRow('選択項目にチェックを入れてください', '<?php $this->basePath(); ?>/file/policy_comparison.xlsx')" class="btn col-sm-2 btn-info pull-right">施策比較表作成</button>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row text-center">
    <ul class="bottom-menu">
        <li class="col-md-1 col-sm-1">

        </li>
        <li class="col-md-2 col-sm-2">
            <a href="home-module-in-create.html" target="_blank">
                <u>
                    サイトポリシー
                </u>
            </a>
        </li>
        <li class="col-md-2 col-sm-2">
            <a href="home-module-in-create.html" target="_blank">
                <u>
                    関連リンク
                </u>
            </a>
        </li>
        <li class="col-md-2 col-sm-2">
            <a href="home-module-in-create.html" target="_blank">
                <u>
                    アクセシビリティ
                </u>
            </a>
        </li>
        <li class="col-md-2 col-sm-2">
            <a href="home-module-in-create.html" target="_blank">
                <u>
                    個人情報保護方針
                </u>
            </a>
        </li>
        <li class="col-md-2 col-sm-2">
            <a href="home-module-in-create.html" target="_blank">
                <u>
                    問い合わせ先
                </u>
            </a>
        </li>
    </ul>
</div>


<!-- =================================================================== -->
<div style ="z-index:99999" id= "policySave" class="modal dialog-position fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">検索条件の保存</h4>
            </div>
            <div class="modal-body" style="width:100%;height:100px;">
                <div>
                    検索条件名 <input type="input" class="form-control " placeholder="">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">キャンセル</button>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#dialogSucceed" data-dismiss="modal">登録</button>
            </div>
        </div>
    </div>
</div>
<div style ="z-index:99999" id= "searchConditionCall" class="modal fade dialog-position" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">検索条件呼び出し</h4>
            </div>
            <div id="popupConfirm" class="modal-body">
                <div>
                    <label class="form-check-input">
                        <input id="id-A1" type="radio" name="rowa1"> サンプル一
                    </label>
                </div>
                <div>
                    <label class="form-check-input">
                        <input id="id-A1" type="radio" name="rowa1"> サンプル二
                    </label>
                </div>
                <div>
                    <label class="form-check-input">
                        <input id="id-A1" type="radio" name="rowa1"> サンプル三
                    </label>
                </div>
                <div>
                    <label class="form-check-input">
                        <input id="id-A1" type="radio" name="rowa1"> サンプル四
                    </label>
                </div>
                <div>
                    <label class="form-check-input">
                        <input id="id-A1" type="radio" name="rowa1"> サンプル五
                    </label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">キャンセル</button>
                <button type="button" onclick="showSaveOption()" class="btn btn-primary" data-dismiss="modal">確認</button>
            </div>
        </div>
    </div>
</div>
<!-- =================================================================== -->
<div class="modal fade" id="boxSearchDetail" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="row">

            <div class="col-sm-12 col-xs-12 container-body">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3>ID: 2-2</h3>
                <div class="box-header">詳細検索</div>
                <div class="row col-md-12">

                    <div class="col-md-3 pull-right">
                        <a href="home-module-1-1-home.html">
                            <button type="button"  class="btn btn-info col-md-12">検索</button>
                        </a>
                    </div>
                </div>
                <div class="box-data">
                    <div class="row">


                    </div>
                    <div class="row col-md-12">
                        <div class="col-md-3 pull-right"><button data-toggle="modal" data-target="#policySave" type="button" class="btn btn-info col-md-12" data-color="primary">検索条件を保存</button></div>
                        <div class="col-md-3 pull-right"><button data-toggle="modal" data-target="#searchConditionCall" type="button" class="btn btn-info col-md-12" data-color="primary">検索条件呼び出し</button></div>
                        <div class="col-md-3 pull-right">
                            <a href="home-module-1-1-home.html">
                                <button type="button"  class="btn btn-info col-md-12">検索</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>