<div class="form-group">
    <label for="inputEmail3" class="col-sm-2 col-xs-12 control-label "><?php echo $attrPolicyType['value'] ?>
        <?php if (!isset($removeRequireFlag) || $removeRequireFlag != 1) {
            if (isset($attrPolicyType['required']) && $attrPolicyType['required'] == 1) {
                ?>
                <span class="flag-notice"> (*)</span>
            <?php }
        }?>
    </label>
    <div class="col-sm-10 col-xs-12 none-distance box-text box-attributes"
         data-id="<?php echo isset($attrPolicyTypeId) ? $attrPolicyTypeId : '' ?>">
        <?php foreach ($attribute as $key => $value) {
            ?>
            <label class="form-check-input <?php echo $key == \Application\Utils\ApplicationConst::NOTICE_RECRUITMENT_FORM_TYPE_3 ? 'col-md-6' : 'col-md-3'; ?>">
                <input class="attributes" type="radio" value="<?php echo $value['id'] ?>"
                       name="attributes[<?php echo isset($attrPolicyTypeId) ? $attrPolicyTypeId : '' ?>][]"
                    <?php echo isset($attributesPolicy) && in_array($value['id'], $attributesPolicy) ? 'checked' : ''; ?>
                       id="attributes_<?php echo $value['id'] ?>"
                       onclick="POLICY.checkRecruitmentTime();"/> <label
                        for="<?php echo 'attributes_' . $value['id'] ?>"></label> <?php echo $value['value'] ?>　
            </label>
        <?php } ?>
        <div class="col-md-12 error-radio"></div>
    </div>
</div>
<div class="form-group">
    <label for="inputEmail3" class="col-sm-2 col-xs-12 control-label "></label>
</div>