<div class="form-group">
    <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label"><?php echo $attrPolicyType['value'] ?>
        <?php if (!isset($removeRequireFlag) || $removeRequireFlag != 1) {
            if (isset($attrPolicyType['required']) && $attrPolicyType['required'] == 1) {
                ?>
                <span class="flag-notice"> (*)</span>
            <?php }
        } ?>
    </label>
    <div class="col-sm-3 col-xs-12 none-distance box-attributes"
         data-id="<?php echo isset($attrPolicyTypeId) ? $attrPolicyTypeId : '' ?>">
        <select class="form-control attributes col-md-12 col-sm-12 col-xs-12" data-title="attributesSelect"
                name="attributesSelect[<?php echo isset($attrPolicyTypeId) ? $attrPolicyTypeId : '' ?>]">
            <?php if (!isset($attrPolicyType['notDefault']) || $attrPolicyType['notDefault'] != 1) { ?>
                <option value=""></option>
            <?php } ?>
            <?php foreach ($attribute as $key => $value) { ?>
                <option value="<?php echo $value['id'] ?>" <?php echo isset($attributesPolicy) && in_array($value['id'], $attributesPolicy) ? 'selected' : ''; ?>><?php echo $value['value'] ?></option>
            <?php } ?>
        </select>
    </div>
</div>