<?php
$datetime = new \DateTime('now');
$dateFormat = \Application\Utils\DateHelper::DATE_FORMAT;
$dateTimeFormat = \Application\Utils\DateHelper::DATE_TIME_FORMAT;
/* @var $policy \Application\Entity\Policy */
$arrPdfFiles = $policy->getPdfFile() ? json_decode($policy->getPdfFile(), true) : array();
?>
<div class="container-body">
    <form id="form-input-policy" method="POST" enctype="multipart/form-data">
        <div class="panel-body" style="padding-right: 15px;">
            <div class="row">
                <div class="title"></div>
                <div class="col-sm-12">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-sm-12 col-xs-12 text-left flag-notice" id="errors-list">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">入力所管部署</label>
                            <div class="col-md-10 col-sm-10 col-xs-12 none-distance">
                                <div class="row">
                                    <div class="col-md-4 col-sm-4">
                                        <select class="form-control btn-space" id="ddlBureauId" name="ddlBureauId">
                                            <option value=""><h5>-- 所属団体 --</h5></option>
                                            <?php foreach ($glConfig['bureauId'] as $key => $value) { ?>
                                                <option value="<?php echo $key; ?>" <?php echo $policy->getBureauId() == $key ? 'selected' : ''; ?>><?php echo $value; ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                    <div class="col-md-4 col-sm-4">
                                        <select class="form-control btn-space" id="ddlDepartmentId" name="ddlDepartmentId">
                                            <option value="">-- 部 --</option>
                                            <?php foreach ($glConfig['departmentId'] as $key => $value) { ?>
                                                <option name="<?php echo $value['parentId'] ?>"
                                                        value="<?php echo $key; ?>" <?php echo $policy->getDepartmentId() == $key ? 'selected' : ''; ?>><?php echo $value['value'] ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                    <div class="col-md-4 col-sm-4">
                                        <select class="form-control btn-space" id="ddlDivisionId" name="ddlDivisionId">
                                            <option value="">-- 課 --</option>
                                            <?php foreach ($glConfig['divisionId'] as $key => $value) {
                                                if ($value['value'] != '') { ?>
                                                    <option name="<?php echo $value['parentId'] ?>"
                                                            value="<?php echo $value['code']; ?>" <?php echo $value['parentId'] == 'departmentId' . $policy->getDepartmentId() && $policy->getDivisionId() == $value['code'] ? 'selected' : ''; ?>><?php echo $value['value'] ?></option>
                                                <?php }
                                            } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">施策略称</label>
                            <div class="col-sm-10 col-xs-12 none-distance ">
                                <input type="content" class="form-control" id="txtShortName" name="txtShortName"
                                       value="<?php echo $policy->getShortName(); ?>"
                                       placeholder="施策略称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">施策名称</label>
                            <div class="col-sm-10 col-xs-12 none-distance btn-space">
                                <input type="content" class="form-control" id="txtName" name="txtName"
                                       value="<?php echo $policy->getName(); ?>" placeholder="施策名称">
                            </div>
                        </div>
                        <?php foreach ($glConfig['attributePolicyType'] as $key => $values) {
                            if (isset($values['displayCreate']) && $values['displayCreate'] == 1) {
                                echo $this->partial('partial-template-attribute-' . $values['templateCreate'] . '.phtml', array(
                                    'attrPolicyType' => $values,
                                    'attributesPolicy' => $attributesPolicy,
                                    'attribute' => isset($attributes[$key]) ? $attributes[$key] : array(),
                                    'attrPolicyTypeId' => $key,
                                    'removeRequireFlag' => 1
                                ));
                            }
                            ?>
                        <?php } ?>
                        <div class="form-group" style="margin-bottom: 0px">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">募集（実施）期間</label>
                            <div class="col-md-6 none-distance">
                                <label class="form-check-input">
                                    <input name="cbRecruitmentFlag" value="1"
                                           onchange="POLICY.checkRecruitmentTime()"
                                           type="checkbox" <?php echo $policy->getRecruitmentFlag() == 1 ? 'checked' : ''; ?>
                                           id="cbRecruitmentFlag" data-toggle="toggle"/><label
                                            for="cbRecruitmentFlag"></label>&nbsp;随時
                                </label>
                            </div>
                        </div>
                        <?php
                        if ($policy->getRecruitmentFlag() != 1 && !in_array(\Application\Utils\ApplicationConst::NOTICE_RECRUITMENT_FORM_TYPE_3, $attributesPolicy)) {
                            $showRecruitmentTime = 1;
                        } else {
                            $showRecruitmentTime = 0;
                        }
                        ?>
                        <div id="box-recruitment-time"
                             style="<?php echo $showRecruitmentTime == 1 ? 'dispay:block' : 'display:none'; ?>"
                             class="form-horizontal">
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label"></label>
                                <h5 id="label-startDate" for="inputPassword3" class="col-sm-3 col-xs-12 text-center">
                                    募集（実施）開始日 </h5>
                                <h5 id="label-endDate" for="inputPassword3" class="col-sm-3 col-xs-12 text-center">
                                    募集（実施）終了日</h5>
                                <h5 id="label-deadline" for="inputPassword3" class="col-sm-3 col-xs-12 text-center ">
                                    募集打切日</h5>
                            </div>
                            <?php
                            $total = count($recruitmentTime) > 0 ? count($recruitmentTime) : 5;
                            for ($i = 0; $i < $total; $i++) {
                                echo $this->partial('partial-template-recruitment-time.phtml', array(
                                    'key' => $i + 1,
                                    'recruitmentTime' => isset($recruitmentTime[$i]) ? $recruitmentTime[$i] : array(),
                                    'isDisableButton' => 1
                                ));
                            } ?>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12 col-xs-12 none-distance">
                                <h5 class="pull-right">※入力枠は文字に従い、縦方向に拡がります。</h5>
                            </div>
                        </div>
                        <?php foreach ($glConfig['attributePolicyType'] as $key => $values) {
                            if (isset($values['displayCreate']) && $values['displayCreate'] == 2) {
                                echo $this->partial('partial-template-attribute-' . $values['templateCreate'] . '.phtml', array(
                                    'attrPolicyType' => $values,
                                    'attributesPolicy' => $attributesPolicy,
                                    'attribute' => isset($attributes[$key]) ? $attributes[$key] : array(),
                                    'attrPolicyTypeId' => $key,
                                    'removeRequireFlag' => 1
                                ));
                            }
                            ?>
                        <?php } ?>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">目的</label>
                            <div class="col-sm-10 col-xs-12 none-distance">
                        <textarea rows="3" onkeyup="COMMON.textAreaAdjust(this,74)" style="overflow:hidden"
                                  type="content"
                                  class="form-control textarea" id="txtPurpose" name="txtPurpose"
                                  placeholder="目的"><?php echo $policy->getPurpose(); ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">対象者の詳細</label>
                            <div class="col-sm-10 col-xs-12 none-distance">
                        <textarea rows="3" onkeyup="COMMON.textAreaAdjust(this,74)" style="overflow:hidden"
                                  type="content"
                                  class="form-control textarea" id="txtDetailOfSupportArea"
                                  name="txtDetailOfSupportArea"
                                  placeholder="対象者の詳細"><?php echo $policy->getDetailOfSupportArea(); ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">施策内容</label>
                            <div class="col-sm-10 col-xs-12 none-distance">
                        <textarea rows="5" onkeyup="COMMON.textAreaAdjust(this,74)" style="overflow:hidden"
                                  type="content"
                                  class="form-control textarea" id="txtContent"
                                  name="txtContent"
                                  placeholder="施策内容"><?php echo $policy->getContent(); ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">募集（実施）期間の詳細</label>
                            <div class="col-sm-10 col-xs-12 none-distance">
                        <textarea rows="3" onkeyup="COMMON.textAreaAdjust(this,74)" style="overflow:hidden"
                                  type="content"
                                  class="form-control textarea" id="txtDetailRecruitmentTime"
                                  name="txtDetailRecruitmentTime"
                                  placeholder="募集（実施）期間の詳細"><?php echo $policy->getDetailRecruitmentTime(); ?></textarea>
                            </div>
                        </div>
                        <?php if ($arrPdfFiles) { ?>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">チラシ・パンフレット</label>
                                <div class="col-sm-10 col-xs-12 none-distance">
                                    <div class="item-policy">
                                        <div class="content">
                                    <span>
                                        <?php
                                        $currentTime = $policy->getCreateDate();
                                        foreach ($arrPdfFiles as $file) { ?>
                                            <a href="<?php echo $this->url('download', array('year' => date('Y', $currentTime), 'month' => date('m', $currentTime), 'day' => date('d', $currentTime), 'fileName' => basename($file))) ?>"
                                               target="_blank">
                                            <img src="<?php echo $this->basePath(); ?>/images/oficina_pdf.png"
                                                 width="40" height="35"
                                                 alt="<?php echo basename($file); ?>" data-toggle="tooltip"
                                                 title="<?php echo basename($file); ?>">
                                        </a>
                                        <?php } ?>
                                    </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">ホームページ</label>
                            <div class="col-sm-10 col-xs-12 none-distance">
                                <input type="texxt" class="form-control textarea" id="txtHomepage" name="txtHomepage"
                                       placeholder="ホームページ" value="<?php echo $policy->getHomepage(); ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">問い合わせ先</label>
                            <div class="col-sm-10 col-xs-12 none-distance">
                        <textarea rows="3" onkeyup="COMMON.textAreaAdjust(this,74)" style="overflow:hidden"
                                  type="content"
                                  class="form-control textarea" id="txtContact" name="txtContact"
                                  placeholder="問い合わせ先"><?php echo $policy->getContact(); ?></textarea>
                            </div>
                        </div>


                        <div id="pendingUpdate" class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">本システムでの</br>
                                公開開始日時</label>

                            <div class="col-sm-3 col-xs-12 input-group date publishDate">

                                <input type='text' class="form-control" name="datePublishStartdate"
                                       id="datePublishStartdate"
                                       value="<?php echo $policy->getPublishStartdate() > 0 ? date($dateTimeFormat, $policy->getPublishStartdate()) : ''; ?>"/>
                                <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                            </div>
                            <label for="inputPassword3"
                                   class="col-sm-2 col-xs-12 col-sm-offset-1 control-label">本システムでの</br>
                                公開終了日時</label>
                            <div class="col-sm-3 col-xs-12 input-group date publishDate">
                                <input type='text' class="form-control" name="datePublishEnddate"
                                       id="datePublishEnddate"
                                       value="<?php echo $policy->getPublishEnddate() > 0 ? date($dateTimeFormat, $policy->getPublishEnddate()) : ''; ?>"/>
                                <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                            </div>
                        </div>
                        <?php if (!isset($this->userInfo['roleId']) || !\Application\Utils\UserHelper::isInputRole($this->userInfo['roleId'])) { ?>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label"></label>
                                <div class="col-md-4 col-sm-4 none-distance">
                                    <label class="form-check-input ">
                                        <input id="cbAttentionFlag" name="cbAttentionFlag" value="1"
                                               type="checkbox" <?php echo $policy->getAttentionFlag() == 1 ? 'checked' : ''; ?>/>
                                        <label for="cbAttentionFlag"></label>
                                        注目フラグ　
                                    </label>
                                </div>
                            </div>
                        <?php } ?>

                        <?php if (!empty($policy->getSummaryUpdate())) { ?>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label">更新内容の概要</label>
                                <div class="col-sm-10 col-xs-12 none-distance">
                            <textarea rows="3" onkeyup="COMMON.textAreaAdjust(this,74)" style="overflow:hidden"
                                      type="content" class="form-control textarea" id="txtSummaryUpdate"
                                      name="txtSummaryUpdate"
                                      placeholder="問い合わせ先"><?php echo $policy->getSummaryUpdate(); ?></textarea>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label"></label>
                            <div class="col-md-4 col-sm-4 none-distance" style="margin-bottom: 0px;">
                                <label class="form-check-input">
                                    <input id="cbEmailNotificationFlag"
                                           name="cbEmailNotificationFlag"
                                           value="1" <?php echo $policy->getEmailNotificationFlag() == 1 ? 'checked' : ''; ?>
                                           type="checkbox"/>
                                    <label for="cbEmailNotificationFlag"></label>
                                    メール通知　
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label"></label>
                            <div class="col-md-10 col-sm-10 none-distance">
                                ※チェックされていると、利用者に施策情報の更新があったことがメール通知されます。
                            </div>
                        </div>
                        <?php if ($policy->getUpdateDateDisplay() > 0) { ?>
                            <div class="form-group" id="update-date-display-box" style="margin-top: 20px;">
                                <label for="inputPassword3"
                                       class="col-sm-2 col-xs-12 control-label">情報更新日（表示用）</label>

                                <div class="col-sm-3 col-xs-12 input-group date inputTime">

                                    <input readonly="true" type='text' class="form-control" name="updateDateDisplay"
                                           id="updateDateDisplay"
                                           value="<?php echo $policy->getUpdateDateDisplay() > 0 ? date($dateFormat, $policy->getUpdateDateDisplay()) : ''; ?>"/>
                                    <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                </div>
                            </div>
                            <div class="form-group" id="update-date-display-note-box">
                                <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label"></label>
                                <div class="col-md-10 col-sm-10 none-distance">
                                    ※施策情報画面の情報更新日欄に表示される日付
                                </div>
                            </div>
                        <?php } ?>
                        <?php if ($typePolicy == 3 && $policy->getUpdateDateSchedule()) { ?>
                            <div class="form-group" id="update-date-box" style="margin-top: 20px;">
                                <label for="inputPassword3"
                                       class="col-sm-2 col-xs-12 control-label">更新内容を反<br>映させる日時</label>

                                <div class="col-sm-3 col-xs-12 input-group date updateDate">

                                    <input readonly="true" type='text' class="form-control" name="updateDate"
                                           id="updateDate"
                                           value="<?php echo $policy->getUpdateDateSchedule() > 0 ? date($dateTimeFormat, $policy->getUpdateDateSchedule()) : ''; ?>"/>
                                    <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 col-xs-12 control-label"></label>
                                <div id="error-update-date"></div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="heighthr"></div>
        <div class="row">
            <div class=" col-sm-2 col-xs-2  pull-right">
                <button type="button" onclick="POLICY.redirectToUrl('<?php echo $refererUrl; ?>');"
                        class="btn btn-primary col-md-12 col-sm-12">
                    一覧へ戻る
                </button>
            </div>
            <div class=" col-sm-2 col-xs-2 pull-right">
                <button type="button" class="btn btn-warning col-sm-12 col-xs-12 ">
                    印刷
                </button>
            </div>

        </div>
    </form>
</div>
<script type="text/javascript"
        src="<?php echo $this->basePath(); ?>/js/policy/policy.js?v=<?php echo \Application\Utils\ApplicationConst::VERSION_STATIC_SOURCE; ?>"></script>
<script>
    $(document).ready(function () {
        POLICY.initSuccess();
    });
</script>